### batch gradient decent 
* for n-D


In [2]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
# y = mx + c c =intercept and m is the coef

In [3]:
X ,y = load_diabetes(return_X_y = True)

In [5]:
X.shape

(442, 10)

In [7]:
X_train,X_test ,y_train ,y_test = train_test_split(X, y ,test_size =0.2 , random_state =2)

In [9]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [10]:
reg.coef_

array([  -9.15865318, -205.45432163,  516.69374454,  340.61999905,
       -895.5520019 ,  561.22067904,  153.89310954,  126.73139688,
        861.12700152,   52.42112238])

In [11]:
reg.intercept_

151.88331005254167

In [12]:
y_pred = reg.predict(X_test)

In [13]:
y_pred

array([154.1213881 , 204.81835118, 124.93755353, 106.08950893,
       258.5348576 , 256.3310074 , 118.75087616, 119.52440696,
       101.50816735, 190.54048661, 141.70656811, 172.51883961,
       174.33861649, 134.80942706, 294.13994537,  94.11798038,
       211.97059795, 156.49579378, 134.21000428, 119.62664644,
       148.87842251, 165.00873409, 151.10021038, 176.04063756,
       133.27769647, 221.29555392, 197.17324941,  96.1577688 ,
        50.26012711, 230.48580317, 242.06073866, 114.11129218,
        67.07532417,  94.52943825, 201.21415375, 167.05136201,
       159.881268  , 192.78746659, 114.49551325, 233.48234551,
       140.82563045, 121.0680409 , 192.27480772, 191.12738845,
       179.16865788, 148.34935601, 163.47414622, 276.81647884,
       100.17926432, 164.10555298, 255.80762189, 136.9466204 ,
       152.37503699, 107.92237882, 194.21924678,  77.34670792,
       118.50482479,  68.38335763, 154.29258529, 162.48840259,
       168.36788326, 156.87790322,  97.14191797, 238.16

In [15]:
r2_score(y_test,y_pred
        )

0.4399338661568968

In [126]:
class GDRegression:
    def __init__(self,learning_rate =0.1, epochs = 100):
        self.coef_ = None
        self.intercept_ = None 
        self.lr = learning_rate
        self.epochs = epochs

    def fit(self,X_train,y_train):
        # initalize
        self.intercept_ =0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            # update the intercept 
            y_hat = np.dot(X_train,self.coef_) + self.intercept_ 
            intercept_der = -2 * (np.mean(y_train - y_hat))
            self.intercept_ = self.intercept_ - (self.lr * intercept_der)

            coef_der = -2 * np.dot((y_train - y_hat),X_train)/X_train.shape[0]
            self.coef_ =self.coef_ - (self.lr *  coef_der)
        print(self.intercept_)
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [127]:
gdr = GDRegression(epochs =900)

In [128]:
gdr.fit(X_train,y_train)

151.88854312408242


In [129]:
gdr.coef_

array([  61.55506862,  -18.7760429 ,  246.30534943,  181.41126467,
         41.30658679,   14.65008509, -135.6871037 ,  120.95134695,
        230.40036467,  115.39106348])

In [130]:
y_pred = gdr.predict(X_test)

In [131]:
r2_score(y_test,y_pred)

0.38795358717987893