In [1]:
# featuring engineering
# encoding the categorical data


In [3]:
# categorical data are tw type
# nominal  and ordinary  
# Nominal data : there is no relation or order ,like state ,there is no order 
# Ordinal : there is a realtion between the data


# label encoding 

In [ ]:
# if the label or outpur column  is a oridinal then it is known as label encoding 


In [45]:
import numpy as np
import pandas as pd




In [46]:
df =pd.read_csv('archive(3)/Mall_Customers.csv')

In [47]:
df.sample(5)

CustomerID   Genre  Age  Annual_Income_(k$)  Spending_Score
20           21    Male   35                  24              35
165         166  Female   36                  85              75
130         131    Male   47                  71               9
73           74  Female   60                  50              56
42           43    Male   48                  39              36

In [48]:
df

CustomerID   Genre  Age  Annual_Income_(k$)  Spending_Score
0             1    Male   19                  15              39
1             2    Male   21                  15              81
2             3  Female   20                  16               6
3             4  Female   23                  16              77
4             5  Female   31                  17              40
..          ...     ...  ...                 ...             ...
195         196  Female   35                 120              79
196         197  Female   45                 126              28
197         198    Male   32                 126              74
198         199    Male   32                 137              18
199         200    Male   30                 137              83

[200 rows x 5 columns]

In [49]:
df = pd.read_csv("customer.csv")

In [51]:
df.sample(5)

age  gender   review education purchased
44   77  Female  Average        UG        No
24   16  Female  Average        PG       Yes
23   96  Female     Good    School        No
5    31  Female  Average    School       Yes
1    68  Female     Poor        UG        No

In [52]:
df = df.iloc[:,2:5]

In [53]:
df

review education purchased
0   Average    School        No
1      Poor        UG        No
2      Good        PG        No
3      Good        PG        No
4   Average        UG        No
5   Average    School       Yes
6      Good    School        No
7      Poor    School       Yes
8   Average        UG        No
9      Good        UG       Yes
10     Good        UG       Yes
11     Good        UG       Yes
12     Poor    School        No
13  Average    School        No
14     Poor        PG       Yes
15     Poor        UG        No
16     Poor        UG       Yes
17     Poor        UG       Yes
18     Good    School        No
19     Poor        PG       Yes
20  Average    School       Yes
21  Average        PG        No
22     Poor        PG       Yes
23     Good    School        No
24  Average        PG       Yes
25     Good    School        No
26     Poor        PG        No
27     Poor        PG        No
28     Poor    School        No
29  Average        UG       Yes
30  Average        UG        No
31     Poor    School       Yes
32  Average        UG       Yes
33     Good        PG       Yes
34  Average    School        No
35     Poor    School       Yes
36     Good        UG       Yes
37  Average        PG       Yes
38     Good    School        No
39     Poor        PG        No
40     Good    School        No
41     Good        PG       Yes
42     Good        PG       Yes
43     Poor        PG        No
44  Average        UG        No
45     Poor        PG       Yes
46     Poor        PG        No
47     Good        PG       Yes
48     Good        UG       Yes
49     Good        UG        No

In [54]:
from sklearn.model_selection import train_test_split

In [55]:
X_train ,X_trest ,y_train,y_test = train_test_split(df.iloc[:,0:2],df.iloc[:,-1],test_size =0.2)

In [56]:
X_train

review education
24  Average        PG
7      Poor    School
1      Poor        UG
12     Poor    School
18     Good    School
33     Good        PG
29  Average        UG
22     Poor        PG
11     Good        UG
4   Average        UG
25     Good    School
16     Poor        UG
40     Good    School
31     Poor    School
35     Poor    School
39     Poor        PG
3      Good        PG
8   Average        UG
47     Good        PG
37  Average        PG
36     Good        UG
2      Good        PG
30  Average        UG
5   Average    School
10     Good        UG
23     Good    School
43     Poor        PG
45     Poor        PG
14     Poor        PG
0   Average    School
42     Good        PG
19     Poor        PG
44  Average        UG
26     Poor        PG
34  Average    School
21  Average        PG
32  Average        UG
28     Poor    School
41     Good        PG
13  Average    School

In [1]:
from sklearn.preprocessing import OrdinalEncoder


In [2]:
#  here the categories decide the  precedence or the value or high value is given to the good then average and then poor and similarly for the education column
oe = OrdinalEncoder(categories = [['Poor','Average','Good'],['School','UG','PG']])

In [58]:
oe.fit(X_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [59]:
X_train = oe.transform(X_train)

In [61]:
X_test = oe.transform(X_trest)

In [62]:
X_train



array([[1., 2.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.]])

In [63]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

In [66]:
X_train

array([[1., 2.],
       [0., 0.],
       [0., 1.],
       [0., 0.],
       [2., 0.],
       [2., 2.],
       [1., 1.],
       [0., 2.],
       [2., 1.],
       [1., 1.],
       [2., 0.],
       [0., 1.],
       [2., 0.],
       [0., 0.],
       [0., 0.],
       [0., 2.],
       [2., 2.],
       [1., 1.],
       [2., 2.],
       [1., 2.],
       [2., 1.],
       [2., 2.],
       [1., 1.],
       [1., 0.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [0., 2.],
       [0., 2.],
       [1., 0.],
       [2., 2.],
       [0., 2.],
       [1., 1.],
       [0., 2.],
       [1., 0.],
       [1., 2.],
       [1., 1.],
       [0., 0.],
       [2., 2.],
       [1., 0.]])

In [78]:
from sklearn.preprocessing import LabelEncoder

In [79]:
le = LabelEncoder()

In [80]:
le.fit(y_train)

LabelEncoder()

In [81]:
LabelEncoder()

LabelEncoder()

In [82]:
le.classes_

array([0, 1])

In [83]:
y_train = le.transform(y_train)
y_test = le.transform(y_test)

In [85]:
y_train

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0])

# ordinal encoding 

In [ ]:
# it is works for ordinal encoding
# when  the data is related with other column