## MINI Batch 

In [1]:
from sklearn.datasets import load_diabetes

import numpy as np
from sklearn.linear_model import LinearRegression 
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
# y = mx + c c =intercept and m is the coef

In [2]:
X ,y = load_diabetes(return_X_y = True)

In [3]:
X_train,X_test ,y_train ,y_test = train_test_split(X, y ,test_size =0.2 , random_state =2)

In [4]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [5]:
y_pred = reg.predict(X_test)

In [6]:
r2_score(y_test,y_pred
        )

0.4399338661568968

In [48]:
import random

class MINIBGDRegression:
    def __init__(self,batch_size, learning_rate =0.1, epochs = 10):
        self.coef_ = None
        self.intercept_ = None 
        self.lr = learning_rate
        self.epochs = epochs
        self.batch_size =batch_size

    def fit(self,X_train,y_train):
        # initalize
        self.intercept_ =0
        self.coef_ = np.ones(X_train.shape[1])

        for i in range(self.epochs):
            # update the intercept 
            for i in range(int(X_train.shape[0]/self.batch_size)):
                idx =random.sample(range(X_train.shape[0]),self.batch_size)
                y_hat = np.dot(X_train[idx],self.coef_) + self.intercept_ 
                intercept_der = -2 * (np.mean(y_train[idx] - y_hat))
                self.intercept_ = self.intercept_ - (self.lr * intercept_der)
    
                coef_der = -2 * np.dot((y_train[idx] - y_hat),X_train[idx])
                self.coef_ =self.coef_ - (self.lr *  coef_der)
    def predict(self,X_test):
        return np.dot(X_test,self.coef_) + self.intercept_

In [41]:
mbr = MINIBGDRegression(batch_size= int(X_train.shape[0]/10) , learning_rate =0.01 ,epochs =35)

In [42]:
mbr.fit(X_train,y_train)

In [43]:
y_pred = mbr.predict(X_test)

In [44]:
r2_score(y_test,y_pred)

0.4139907413304297

In [45]:
mbr.coef_

array([  59.78444723,  -38.86688013,  299.29976038,  218.25608172,
         32.58502294,   -3.49698214, -151.61415976,  123.26285774,
        274.12503326,  126.64534887])

In [47]:
mbr.intercept_

151.77313295154664

### sklearn in-built

In [49]:
from sklearn.linear_model import SGDRegressor


In [65]:
sgd = SGDRegressor(learning_rate='constant',eta0=0.01)

In [69]:
batch_size = 35 
for i in range(100):
    idx =random.sample(range(X_train.shape[0]),batch_size)
    sgd.partial_fit(X_train,y_train)

In [70]:
sgd.coef_

array([  31.39131476, -133.50604522,  440.65227926,  298.29929965,
        -19.20823642,  -86.451745  , -189.48985666,  113.78999562,
        399.3480548 ,  114.28108203])

In [71]:
sgd.intercept_

array([151.49997491])