In [12]:
import pickle
import numpy as np

In [13]:
ohe_sex = pickle.load(open('ohe_sex.pkl','rb'))
ohe_embarked = pickle.load(open('ohe_embarked.pkl','rb'))
clf = pickle.load(open('clf.pkl','rb'))

In [14]:
# Assume user input 
# pClass /gender/age /SibSp/Prach /fare/Ebmbarked

test_input = np.array([2,'male',31.0,0,0,10.5,'S'],dtype = object).reshape(1,7)

In [15]:
test_input

array([[2, 'male', 31.0, 0, 0, 10.5, 'S']], dtype=object)

In [16]:
test_input_sex = ohe_sex.transform(test_input[:,1].reshape(1,1))
test_input_sex

/home/anubhav/.local/lib/python3.10/site-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 1.]])

In [17]:
test_input_embarked = ohe_embarked.transform(test_input[:,-1].reshape(1,1))


In [18]:
test_input_age = test_input[:,2].reshape(1,1)

In [19]:
test_input_embarked

array([[0., 0., 1.]])

In [20]:
test_transformed = np.concatenate((test_input[:,[0,3,4,5]],test_input_age,test_input_sex,test_input_embarked),axis=1)

In [21]:
test_transformed.shape

(1, 10)

In [22]:
clf.predict(test_transformed)

array([1])